In [1]:
from math import pi as PI
import pandas as pd
df = pd.read_csv('data.csv', dtype=str)

In [2]:
tuple(df.columns.values)

('Unnamed: 0',
 'Bird Species',
 'Coordinates',
 'Date',
 'Distance Bin',
 'Group Name',
 'Habitat Type',
 'Location',
 'Remarks',
 'Time',
 'Time Period')

# Simplify data
by removing useless columns
- `Unnamed: 0` is a side effect column from preprocess
- `Coordinates` is too varied in formatting and accuracy to use
- `Date` is not useful information, because all within a few days
- `Remarks` does not provide additional useful information

In [3]:
df.drop(['Unnamed: 0', 'Coordinates', 'Date', 'Remarks'],
    axis=1, inplace=True)

In [4]:
tuple(df.columns.values)

('Bird Species',
 'Distance Bin',
 'Group Name',
 'Habitat Type',
 'Location',
 'Time',
 'Time Period')

In [5]:
df.iloc[0]['Location']

'8 Kent Ridge Drive (Just outside Ventus)'

In [6]:
# identify unique locs by concat group name & loc
lagging_pointer = '{}---{}'.format(
    df.iloc[0]['Group Name'], df.iloc[0]['Location'])
current_pointer = ''
last_time_period = ''

species_counter = {
    'Black-naped oriole': 0,
    'Javan myna': 0,
    'Olive-backed sunbird': 0,
    'Rock pigeon': 0,
    'Yellow-vented bulbul': 0
}

count_per_site_df = pd.DataFrame()

for _, row in df.iterrows():
    current_pointer = '{}---{}'.format(row[2], row[4])
    if current_pointer == lagging_pointer:
        # still on the same site
        species_counter[row[0]] += 1
    else:
        # current_pointer is on a new site
        # first, save the information
        for species, count in species_counter.items():
            count_per_site_df = count_per_site_df.append(
                {
                    'Bird Species': species,
                    'Count': count,
                    'Density': count / (PI * 0.25 ** 2),
                    'Location': lagging_pointer,
                    'Time Period': last_time_period
                }
                , ignore_index=True
            )
        # reset the species_counter...
        species_counter = {
            'Black-naped oriole': 0,
            'Javan myna': 0,
            'Olive-backed sunbird': 0,
            'Rock pigeon': 0,
            'Yellow-vented bulbul': 0
        }
        # then, count current_pointer
        species_counter[row[0]] += 1
    # move lagging_pointer up
    lagging_pointer = current_pointer
    last_time_period = row[6]

# clean up the last site
for species, count in species_counter.items():
    count_per_site_df = count_per_site_df.append(
        {
            'Bird Species': species,
            'Count': count,
            'Density': count / (PI * 0.25 ** 2),
            'Location': lagging_pointer,
            'Time Period': last_time_period
        }, ignore_index=True)

In [7]:
count_per_site_df

,Bird Species,Count,Density,Location,Time Period
0,Rock pigeon,0.0,0.000000,Asian Koel---8 Kent Ridge Drive (Just outside ...,0932
1,Olive-backed sunbird,1.0,5.092958,Asian Koel---8 Kent Ridge Drive (Just outside ...,0932
2,Javan myna,0.0,0.000000,Asian Koel---8 Kent Ridge Drive (Just outside ...,0932
3,Yellow-vented bulbul,0.0,0.000000,Asian Koel---8 Kent Ridge Drive (Just outside ...,0932
4,Black-naped oriole,2.0,10.185916,Asian Koel---8 Kent Ridge Drive (Just outside ...,0932
5,Rock pigeon,0.0,0.000000,Asian Koel---11 Arts Link (Outside AS5 facing ...,1005
6,Olive-backed sunbird,1.0,5.092958,Asian Koel---11 Arts Link (Outside AS5 facing ...,1005
7,Javan myna,0.0,0.000000,Asian Koel---11 Arts Link (Outside AS5 facing ...,1005
8,Yellow-vented bulbul,0.0,0.000000,Asian Koel---11 Arts Link (Outside AS5 facing ...,1005
9,Black-naped oriole,0.0,0.000000,Asian Koel---11 Arts Link (Outside AS5 facing ...,1005
10,Rock pigeon,0.0,0.000000,Asian Koel---15 Kent Ridge Drive (Opp Hon Sui ...,1035
11,Olive-backed sunbird,1.0,5.092958,Asian Koel---15 Kent Ridge Drive (Opp Hon Sui ...,1035
12,Javan myna,0.0,0.000000,Asian Koel---15 Kent Ridge Drive (Opp Hon Sui ...,1035
13,Yellow-vented bulbul,3.0,15.278875,Asian Koel---15 Kent Ridge Drive (Opp Hon Sui ...,1035
14,Black-naped oriole,1.0,5.092958,Asian Koel---15 Kent Ridge Drive (Opp Hon Sui ...,1035
15,Rock pigeon,22.0,112.045080,Asian Koel---3 Research Link (End of D1 Bus te...,1055
16,Olive-backed sunbird,2.0,10.185916,Asian Koel---3 Research Link (End of D1 Bus te...,1055
17,Javan myna,3.0,15.278875,Asian Koel---3 Research Link (End of D1 Bus te...,1055
18,Yellow-vented bulbul,5.0,25.464791,Asian Koel---3 Research Link (End of D1 Bus te...,1055
19,Black-naped oriole,0.0,0.000000,Asian Koel---3 Research Link (End of D1 Bus te...,1055
20,Rock pigeon,2.0,10.185916,Spotted Dove---NUS Medical Drive near NUS Grad...,0925
21,Olive-backed sunbird,2.0,10.185916,Spotted Dove---NUS Medical Drive near NUS Grad...,0925
22,Javan myna,7.0,35.650707,Spotted Dove---NUS Medical Drive near NUS Grad...,0925
23,Yellow-vented bulbul,1.0,5.092958,Spotted Dove---NUS Medical Drive near NUS Grad...,0925
24,Black-naped oriole,0.0,0.000000,Spotted Dove---NUS Medical Drive near NUS Grad...,0925
25,Rock pigeon,0.0,0.000000,Spotted Dove---LKCNM,0925
26,Olive-backed sunbird,0.0,0.000000,Spotted Dove---LKCNM,0925
27,Javan myna,0.0,0.000000,Spotted Dove---LKCNM,0925
28,Yellow-vented bulbul,1.0,5.092958,Spotted Dove---LKCNM,0925
29,Black-naped oriole,0.0,0.000000,Spotted Dove---LKCNM,0925
...,...,...,...,...,...
865,Rock pigeon,2.0,10.185916,Crimson Sunbird---Between S12 and S13,1048
866,Olive-backed sunbird,0.0,0.000000,Crimson Sunbird---Between S12 and S13,1048
867,Javan myna,1.0,5.092958,Crimson Sunbird---Between S12 and S13,1048
868,Yellow-vented bulbul,0.0,0.000000,Crimson Sunbird---Between S12 and S13,1048
869,Black-naped oriole,0.0,0.000000,Crimson Sunbird---Between S12 and S13,1048
870,Rock pigeon,1.0,5.092958,Crimson Sunbird---Behind opposite Kent Ridge M...,1121
871,Olive-backed sunbird,0.0,0.000000,Crimson Sunbird---Behind opposite Kent Ridge M...,1121
872,Javan myna,0.0,0.000000,Crimson Sunbird---Behind opposite Kent Ridge M...,1121
873,Yellow-vented bulbul,3.0,15.278875,Crimson Sunbird---Behind opposite Kent Ridge M...,1121
874,Black-naped oriole,0.0,0.000000,Crimson Sunbird---Behind opposite Kent Ridge M...,1121
875,Rock pigeon,0.0,0.000000,Crimson Sunbird---Opposite Shaw Foundation Bui...,1500
876,Olive-backed sunbird,1.0,5.092958,Crimson Sunbird---Opposite Shaw Foundation Bui...,1500
877,Javan myna,0.0,0.000000,Crimson Sunbird---Opposite Shaw Foundation Bui...,1500
878,Yellow-vented bulbul,1.0,5.092958,Crimson Sunbird---Opposite Shaw Foundation Bui...,1500
879,Black-naped oriole,1.0,5.092958,Crimson Sunbird---Opposite Shaw Foundation Bui...,1500
880,Rock pigeon,0.0,0.000000,"Crimson Sunbird---Along Business Link, near He...",1520
881,Olive-backed sunbird,0.0,0.000000,"Crimson Sunbird---Along Business Link, near He...",1520
882,Javan myna,1.0,5.092958,"Crimson Sunbird---Along Business Link, near He...",1520
883,Yellow-vented bulbul,0.0,0.000000,"Crimson Sunbird---Along Business Link, near He...",1520
884,Black-naped oriole,0.0,0.000000,"Crimson Sunbird---Along Business Link, near He...",1520
885,Rock pigeon,0.0,0.000000,Crimson Sunbird---Prince George's Park,1545
886,Olive-backed sunbird,0.0,0.000000,Crimson Sunbird---Prince George's Park,1545
887,Javan myna,1.0,5.092958,Crimson Sunbird---Prince George's Park,1545
888,Yellow-vented bulbul,0.0,0.000000,Crimson Sunbird---Prince George's Park,1545
889,Black-naped oriole,0.0,0.000000,Crimson Sunbird---Prince George's Park,1545
890,Rock pigeon,0.0,0.000000,Spotted Wood Owl---Behind South Tower,0934
891,Olive-backed sunbird,0.0,0.000000,Spotted Wood Owl---Behind South Tower,0934
892,Javan myna,0.0,0.000000,Spotted Wood Owl---Behind South Tower,0934
893,Yellow-vented bulbul,8.0,40.743665,Spotted Wood Owl---Behind South Tower,0934
894,Black-naped oriole,0.0,0.000000,Spotted Wood Owl---Behind South Tower,0934

In [8]:
for i, row in df.iterrows():
    df.loc[i, 'Location'] = row[2] + '---' + row[4]

In [9]:
print('len(count_per_site_df): {}\nlen(df): {}'.format(
    len(count_per_site_df), len(df)))
print('len(set(count_per_site_df[\'Location\'])): {}'.format(
    len(set(count_per_site_df['Location']))))
print('len(set(df[\'Location\'])): {}'.format(
    len(set(df['Location']))))

len(count_per_site_df): 895
len(df): 999
len(set(count_per_site_df['Location'])): 179
len(set(df['Location'])): 179

In [10]:
empty_sites = 200 - len(set(count_per_site_df['Location']))

for i in range(empty_sites):
    for species in species_counter.keys():
        count_per_site_df = count_per_site_df.append(
            {
                'Bird Species': species,
                'Count': 0,
                'Density': 0,
                'Location': 'empty{}'.format(i+1),
                'Time Period': None
            }, ignore_index=True
        )

In [11]:
print('len(count_per_site_df): {}\nlen(df): {}'.format(
    len(count_per_site_df), len(df)))
print('len(set(count_per_site_df[\'Location\'])): {}'.format(
    len(set(count_per_site_df['Location']))))
print('len(set(df[\'Location\'])): {}'.format(
    len(set(df['Location']))))

len(count_per_site_df): 1000
len(df): 999
len(set(count_per_site_df['Location'])): 200
len(set(df['Location'])): 179

In [12]:
count_per_site_df

,Bird Species,Count,Density,Location,Time Period
0,Rock pigeon,0.0,0.000000,Asian Koel---8 Kent Ridge Drive (Just outside ...,0932
1,Olive-backed sunbird,1.0,5.092958,Asian Koel---8 Kent Ridge Drive (Just outside ...,0932
2,Javan myna,0.0,0.000000,Asian Koel---8 Kent Ridge Drive (Just outside ...,0932
3,Yellow-vented bulbul,0.0,0.000000,Asian Koel---8 Kent Ridge Drive (Just outside ...,0932
4,Black-naped oriole,2.0,10.185916,Asian Koel---8 Kent Ridge Drive (Just outside ...,0932
5,Rock pigeon,0.0,0.000000,Asian Koel---11 Arts Link (Outside AS5 facing ...,1005
6,Olive-backed sunbird,1.0,5.092958,Asian Koel---11 Arts Link (Outside AS5 facing ...,1005
7,Javan myna,0.0,0.000000,Asian Koel---11 Arts Link (Outside AS5 facing ...,1005
8,Yellow-vented bulbul,0.0,0.000000,Asian Koel---11 Arts Link (Outside AS5 facing ...,1005
9,Black-naped oriole,0.0,0.000000,Asian Koel---11 Arts Link (Outside AS5 facing ...,1005
10,Rock pigeon,0.0,0.000000,Asian Koel---15 Kent Ridge Drive (Opp Hon Sui ...,1035
11,Olive-backed sunbird,1.0,5.092958,Asian Koel---15 Kent Ridge Drive (Opp Hon Sui ...,1035
12,Javan myna,0.0,0.000000,Asian Koel---15 Kent Ridge Drive (Opp Hon Sui ...,1035
13,Yellow-vented bulbul,3.0,15.278875,Asian Koel---15 Kent Ridge Drive (Opp Hon Sui ...,1035
14,Black-naped oriole,1.0,5.092958,Asian Koel---15 Kent Ridge Drive (Opp Hon Sui ...,1035
15,Rock pigeon,22.0,112.045080,Asian Koel---3 Research Link (End of D1 Bus te...,1055
16,Olive-backed sunbird,2.0,10.185916,Asian Koel---3 Research Link (End of D1 Bus te...,1055
17,Javan myna,3.0,15.278875,Asian Koel---3 Research Link (End of D1 Bus te...,1055
18,Yellow-vented bulbul,5.0,25.464791,Asian Koel---3 Research Link (End of D1 Bus te...,1055
19,Black-naped oriole,0.0,0.000000,Asian Koel---3 Research Link (End of D1 Bus te...,1055
20,Rock pigeon,2.0,10.185916,Spotted Dove---NUS Medical Drive near NUS Grad...,0925
21,Olive-backed sunbird,2.0,10.185916,Spotted Dove---NUS Medical Drive near NUS Grad...,0925
22,Javan myna,7.0,35.650707,Spotted Dove---NUS Medical Drive near NUS Grad...,0925
23,Yellow-vented bulbul,1.0,5.092958,Spotted Dove---NUS Medical Drive near NUS Grad...,0925
24,Black-naped oriole,0.0,0.000000,Spotted Dove---NUS Medical Drive near NUS Grad...,0925
25,Rock pigeon,0.0,0.000000,Spotted Dove---LKCNM,0925
26,Olive-backed sunbird,0.0,0.000000,Spotted Dove---LKCNM,0925
27,Javan myna,0.0,0.000000,Spotted Dove---LKCNM,0925
28,Yellow-vented bulbul,1.0,5.092958,Spotted Dove---LKCNM,0925
29,Black-naped oriole,0.0,0.000000,Spotted Dove---LKCNM,0925
...,...,...,...,...,...
970,Rock pigeon,0.0,0.000000,empty16,None
971,Olive-backed sunbird,0.0,0.000000,empty16,None
972,Javan myna,0.0,0.000000,empty16,None
973,Yellow-vented bulbul,0.0,0.000000,empty16,None
974,Black-naped oriole,0.0,0.000000,empty16,None
975,Rock pigeon,0.0,0.000000,empty17,None
976,Olive-backed sunbird,0.0,0.000000,empty17,None
977,Javan myna,0.0,0.000000,empty17,None
978,Yellow-vented bulbul,0.0,0.000000,empty17,None
979,Black-naped oriole,0.0,0.000000,empty17,None
980,Rock pigeon,0.0,0.000000,empty18,None
981,Olive-backed sunbird,0.0,0.000000,empty18,None
982,Javan myna,0.0,0.000000,empty18,None
983,Yellow-vented bulbul,0.0,0.000000,empty18,None
984,Black-naped oriole,0.0,0.000000,empty18,None
985,Rock pigeon,0.0,0.000000,empty19,None
986,Olive-backed sunbird,0.0,0.000000,empty19,None
987,Javan myna,0.0,0.000000,empty19,None
988,Yellow-vented bulbul,0.0,0.000000,empty19,None
989,Black-naped oriole,0.0,0.000000,empty19,None
990,Rock pigeon,0.0,0.000000,empty20,None
991,Olive-backed sunbird,0.0,0.000000,empty20,None
992,Javan myna,0.0,0.000000,empty20,None
993,Yellow-vented bulbul,0.0,0.000000,empty20,None
994,Black-naped oriole,0.0,0.000000,empty20,None
995,Rock pigeon,0.0,0.000000,empty21,None
996,Olive-backed sunbird,0.0,0.000000,empty21,None
997,Javan myna,0.0,0.000000,empty21,None
998,Yellow-vented bulbul,0.0,0.000000,empty21,None
999,Black-naped oriole,0.0,0.000000,empty21,None

In [13]:
count_per_site_df.Count = count_per_site_df.Count.astype(int)

In [14]:
count_per_site_df.to_csv('counts_per_site.csv')